### ISSUE TITLE
Installation error: unable to find libcrispr

### ISSUE THREAD

**Issue by shaman-narayanasamy** [ctSkennerton/crisprtools#10]
Hi,

I am getting the following error when running `./configure`:

```
configure: error: Cannot find libcrispr
```

I installed libcrispr with no issues prior to this. Is there something I should do after the installation? I.e. Adding to a path of some sort?

**Comment by ctSkennerton** [comment]
Check your crass installation, I believe that crisprtools now gets installed automatically with crass

**Comment by shaman-narayanasamy** [comment]
Indeed it is. Thanks again! :)
