### ISSUE TITLE
Controlling extracted output names and headers

### ISSUE THREAD

**Issue by shaman-narayanasamy** [ctSkennerton/crisprtools#11]
Hi!

I am trying to run `crisprtools extract` on output from `crass`. I would like the files to be present within a specific folder: `A02/crass_mt-reads/` and I want the files to have a name of `crass_mt-reads_[spacers/repeats/flanks].fa`. I therefore used the `-o` to specify the folder and `-O` to specify the file name. I also want the fasta headers to contain "A02_crass_mt-reads" before anything. And I attempted setting it using the `-H` option. Below is my command:

```
$ crisprtools extract /scratch/users/snarayanasamy/LAO_TS_CRISPR/A02/crass_mg-reads/crass.crispr -sspacers.fa -drepeats.fa -fflanks.fa -oA02/crass_mt-reads/ -Ocrass_mt-reads_ -HA02_crass_mt-reads_
```

However, when I check my output folder. I don't find what was expected.

```
$ ls A02/crass_mt-reads/
A02_crass_mt-reads_flanks.fa  A02_crass_mt-reads_repeats.fa  A02_crass_mt-reads_spacers.fa
```

The names which supposed to be in the headers are also appended on the file. Perhaps I am doing something wrong here or is this the expected behaviour?

Best regards,
Shaman

**Comment by ctSkennerton** [comment]
The `-H` option adds the prefix to both the file name and to the fasta headers, can you open up the output files to make sure that it's the case.

**Comment by shaman-narayanasamy** [comment]
Yes, that is indeed the case. The header names appear as I want. I just would like the file name to be different. 

This seems to work, for my case:

```
crisprtools extract A02/crass_mt-reads/crass.crispr -sspacers.fa -drepeats.fa -fflanks.fa -HA02/crass_mt-reads/crass_mt-reads_
```

However, I do end up with the slashes in the fasta header, which should be fixed with a one-liner using `sed` :)

-Shaman-
